Input must have parent's width
narqo/bem-suggest pull request #38
Opened 2016-11-18 12:57 UTC by gela-d

Если саджесту установить какую-то ширину в пикселях, то инпут не растянется по родителю.

2016-11-18 13:26 UTC, narqo commented
Может лучше использовать `input_width_available`?

2016-11-18 13:27 UTC, gela-d commented
Кажется, что тогда будет пересечение с `.suggest_width_available`. 
Или пофиг, всегда используем такой инпут и все?

2016-11-18 14:35 UTC, narqo commented
Мне кажется, что если можно безболезненно вставлять `input_width_available`, то лучше однозначно брать его.

2016-11-18 15:45 UTC, gela-d commented
Апнула, сосквошу потом, если все ок.

2016-11-18 16:13 UTC, narqo requested changes
Сможешь поправить тесты на шаблоны?

2016-11-18 16:13 UTC, narqo commented on blocks/suggest/__control/suggest__control.bemhtml
> +            mods : this.extend({ width: 'available' }, this.elemMods || {}),
`|| {}` не нужно

2016-11-18 16:36 UTC, gela-d commented
Все поправила, сосквошила, апнула.

2016-11-18 17:16 UTC, narqo approved these changes

2016-11-18 17:16 UTC, merged

2016-11-18 19:26 UTC, gela-d commented
Спасибо! Вов, а версия не планируется, а то мы не хэше сидим :)

2016-11-18 19:28 UTC, narqo commented
Так я же поставил тег 0.3.0

2016-11-21 05:43 UTC, gela-d commented
Спасибо!